version: '3'
services:
    dynamo:
        image: 'amazon/dynamodb-local:1.13.4'
        ports:
            - 8000:8000
        networks:
            app-network:
    batch:
        build: .
        volumes:
            - ./:/go/src/app
        networks:
            app-network:
        depends_on:
            - dynamo

networks:
    app-network:
        driver: bridge
